### ISSUE TITLE
change previewThumbnail parameter dynamically

### ISSUE THREAD

**Issue by Kuuzou-cl** [redxtech/vue-plyr#114]
is there any more documentation or examples about the parameters or how to implement them in a component in vuejs, i could not find any in Plyr and i'm struggling a lot to find an answer, 

i got this part
`import VuePlyr from "vue-plyr";`
`Vue.use(VuePlyr, {
  plyr: {
    previewThumbnails: {
      enabled: true,
      src: ""
    }
  }
});`
and its working if i put a path in the src parameter, like /assets/vtt.vtt, but it will show the same in every video, so in a view like Video.vue like this

`<vue-plyr>
            <video preload="auto" controls nativeControlsForTouch :poster="this.video.imageUrl">
              <source :src="this.video.url" type="video/mp4" />
            </video>
          </vue-plyr>`

what should i add to change de src of previewThumbnails?

**Comment by redxtech** [comment]
Instead of setting `previewThumbnails` in the initialization part (that part is specifically to have global settings that apply to all players), you can [set it in the options prop](/redxtech/vue-plyr#options).

For your options object just include this (but set the source to the file specific to that player instance):
```js
{
    previewThumbnails: { enabled: true, src: "thumbs.vtt" }
}
```

I'll close this for now, but if this doesn't work then feel free to re-open your issue and we'll see what we can do.
