### ISSUE TITLE
无法退出全屏

### ISSUE THREAD

**Issue by apacheao** [redxtech/vue-plyr#124]
无法退出全屏

**Comment by redxtech** [comment]
First, I do not speak chinese, so anything I respond to is based on google translate. I would appreciate if all support related to this project was done in english so that I am able to help you.

Also, since google translate tells me that you're unable to exit fullscreen, would you be able to provide more details? Preferably in english?

**Comment by redxtech** [comment]
Since you haven't responded in a while I'm going to close this.
