### ISSUE TITLE
How can I solve this error when dev-server with webpack?

### ISSUE THREAD

**Issue by agreadname** [redxtech/vue-plyr#137]
Module parse failed: Unexpected token (234:53)
You may need an appropriate loader to handle this file type.
| VuePlyr.install = (Vue, options = {}) => {
|   if (options.plyr) {
|     VuePlyr.props.options.default = () => { return { ...options.plyr } };
|   }
|   if (options.emit) {

 @ ./src/main.js 106:0-31
 @ multi (webpack)-dev-server/client?http://192.168.89.183:81 webpack/hot/dev-server ./node_modules/babel-polyfill/dist/polyfill.js ./src/main.js

**Comment by frutality** [comment]
Have you solved this? I'm getting same error when trying to upgrade to v6.

v3, v4 and v5 works fine for me.

Seems like config issue. Webpack for some reason thinks something wrong with spread (...) operator. There is a solution to this described [here](https://stackoverflow.com/questions/50327580/webpack-4-react-unexpected-token-spread-operator): use `babel-plugin-transform-object-rest-spread`.

But I am using it and still getting error. I think problem is with `.mjs` extension, because before v6 vue-plyr used old-fashion `.js`.

Problem is that I can't figure what should be configured in Webpack to catch mjs files.

**Comment by frutality** [comment]
Apparently problem solved by updating laravel-mix which caused to update babel and webpack.

**Comment by redxtech** [comment]
Yeah, this would be caused by your tooling not recognizing the mjs format.
