### ISSUE TITLE
sampotts/plyr.git develop Permission denied

### ISSUE THREAD

**Issue by reaink** [redxtech/vue-plyr#474]
```
 ERROR  Command failed with exit code 128: /usr/bin/git ls-remote --refs git+ssh://git@github.com/sampotts/plyr.git develop
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by nietonfir** [comment]
That's because the dependency on plyr is defined through a [github URL](https://github.com/redxtech/vue-plyr/blob/master/package.json#L31), which npm apparently translates to `git+ssh://git@github.com/sampotts/plyr.git`. And for ssh access to github you need SSH-keys configured in your github account.

The easiest way for you would be to install the plyr dependency by yourself: `npm i plyr`

Please keep in mind, that this could result in problems as this repo has not seen any updates for quite some time while plyr development continued, so you might need to downgrade to an older version of plyr instead. Assuming plyr honors semver you should be fine though.

**Comment by nietonfir** [comment]
Well, that did not solve it completely.

What did work on the other hand was forcing an override: 

```json
  "overrides": {
    "vue-plyr": {
      "plyr": "^3.7.0"
    }
  },
```

This is a relative new npm feature introduced in v8.3, see https://stackoverflow.com/a/70396201/838733 and https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides

**Comment by reaink** [comment]
@nietonfir Thank you, I use @hulkapps/vue-plyr fork package can work
