### ISSUE TITLE
[Vue warn]: Error in mounted hook: "TypeError: Object doesn't support this action" on IE11

### ISSUE THREAD

**Issue by erickespinoza** [redxtech/vue-plyr#66]
Looks like for some reason VuePlyr.vue is not using the plyr.polyfilled.js this is causing the issue that the video player is not working on IE11, is there any way to use without using the polyfill.io suggestion on plyr github, since the server doesn't support cdn requests.

**Comment by redxtech** [comment]
How are you using polyfill.io? It appears as if its entire service is based around the fact that it can be used as an API & CDN. Are you loading it before you load plyr?

**Comment by ilostit** [comment]
Hi, same issue here, at the end what's the best approach ?

**Comment by gobrightspot** [comment]
I'm experiencing this too. It's trying to use Array.protoype.find but polyfill.io doesn't seem to poly fill that correctly...

I'm loading the polyfill.io script before my own script.

**Comment by redxtech** [comment]
Hmm that's odd. Not sure what's going on there.
My recommendation is opening an issue on the upstream source [here](/sampotts/plyr) and describe the issue. In your issue make sure to let him know that you're using vue-plyr and that I sent you there.
Make sure to link to this issue so that we can see what's going on.

**Comment by redxtech** [comment]
Since there haven't any updates I'm going to close this issue. Feel free to reopen if you still have issues.
